version: '2.0'
services:
  namenode:
    image: lkx810/hadoop-namenode:2.8.5
    hostname: namenode
    container_name: namenode
    ports:
      - "50070:50070"       # web
      - "8020:8020"         # ipc
    volumes:
      - namenode:/hadoop/dfs/name
    depends_on:
      - historyserver
    env_file:
      - ./hadoop.env
    environment:
      - CLUSTER_NAME=hadoop

  resourcemanager:
    image: lkx810/hadoop-resourcemanager:2.8.5
    hostname: resourcemanager
    container_name: resourcemanager
    ports:
      - "8088:8088"         # resourcemanager web
      - "8030:8030"         # resourcemanager ipc
      - "8031:8031"         # resourcemanager ipc
      - "8032:8032"         # resourcemanager ipc
    depends_on:
      - historyserver
    env_file:
      - ./hadoop.env

  historyserver:
    image: lkx810/hadoop-historyserver:2.8.5
    hostname: historyserver
    container_name: historyserver
    ports:
      - "8188:8188"         # historyserver log server web
      - "19888:19888"       # mr jobhistory web
      - "10020:10020"       # mr jobhistory ipc
    env_file:
      - ./hadoop.env

  nodemanager1:
    image: lkx810/hadoop-nodemanager:2.8.5
    hostname: nodemanager1
    container_name: nodemanager1
    ports:
      - "8042:8042"
    depends_on:
      - namenode
      - resourcemanager
      - datanode1
      - datanode2
    env_file:
      - ./hadoop.env

  datanode1:
    image: lkx810/hadoop-datanode:2.8.5
    hostname: datanode1
    container_name: datanode1
    depends_on:
      - namenode
      - resourcemanager
    volumes:
      - datanode1:/hadoop/dfs/data
    env_file:
      - ./hadoop.env

  datanode2:
    image: lkx810/hadoop-datanode:2.8.5
    hostname: datanode2
    container_name: datanode2
    depends_on:
      - namenode
      - resourcemanager
    volumes:
      - datanode2:/hadoop/dfs/data
    env_file:
      - ./hadoop.env

# storage hadoop file
volumes:
  namenode:
  datanode1:
  datanode2:
