version: '2.0'
services:
  namenode:
    image: lkx810/hadoop-namenode:2.8.5
    hostname: namenode
    container_name: namenode
    ports:
      - "50070:50070"
      - "8020:8020"
    volumes:
      - namenode:/hadoop/dfs/name
    env_file:
      - ./hadoop.env
    environment:
      - CLUSTER_NAME=hadoop

  resourcemanager:
    image: lkx810/hadoop-resourcemanager:2.8.5
    hostname: resourcemanager
    container_name: resourcemanager
    ports:
      - "8088:8088"
      - "8031:8031"
      - "8032:8032"
      - "8030:8030"
    depends_on:
      - namenode
      - datanode1
      - datanode2
      - historyserver
    env_file:
      - ./hadoop.env

  historyserver:
    image: lkx810/hadoop-historyserver:2.8.5
    hostname: historyserver
    container_name: historyserver
    env_file:
      - ./hadoop.env

  nodemanager1:
    image: lkx810/hadoop-nodemanager:2.8.5
    hostname: nodemanager1
    container_name: nodemanager1
    depends_on:
      - namenode
      - datanode1
      - datanode2
    env_file:
      - ./hadoop.env

  datanode1:
    image: lkx810/hadoop-datanode:2.8.5
    hostname: datanode1
    container_name: datanode1
    ports:
      - "50075:50075"
    depends_on:
      - namenode
    volumes:
      - datanode1:/hadoop/dfs/data
    env_file:
      - ./hadoop.env

  datanode2:
    image: lkx810/hadoop-datanode:2.8.5
    hostname: datanode2
    container_name: datanode2
    depends_on:
      - namenode
    volumes:
      - datanode2:/hadoop/dfs/data
    env_file:
      - ./hadoop.env

volumes:
  namenode:
  datanode1:
  datanode2:
